### PR TITLE
error msg wasn't descriptive enough

### PR DESCRIPTION
**Pull request by moooooooo**
i was having difficulty using zelcash-cli backupwallet

### CODE REVIEW

**Comment by TheTrunk** [comment]
I am suggesting offering a possibility to enter a destination of the backup wallet as a parameter.
Like it was done in the scenario of dumpwallet 
9772494f4e6f9200e9350260cbae7f582522fb7a

**Comment by moooooooo** [comment]
> I am suggesting offering a possibility to enter a destination of the backup wallet as a parameter.
> Like it was done in the scenario of dumpwallet
> [9772494](https://github.com/zelcash/zelcash/commit/9772494f4e6f9200e9350260cbae7f582522fb7a)

I just did that and was just opening rpcdump.cpp to see the code in there. I'm happy to change the code, test and re-push it

**Comment by moooooooo** [comment]
i'll use the same code that's in rpcdump.cpp after sanitising it as well. I'll check the following:
dumpwallet
z_exportwallet

as when i did z_exportwallet there were a few things that could have had better wording/hints!! I'll get some sleep (just after 4am here) and look at it later this morning.

**Comment by moooooooo** [comment]
> I am suggesting offering a possibility to enter a destination of the backup wallet as a parameter.
> Like it was done in the scenario of dumpwallet
> [9772494](https://github.com/zelcash/zelcash/commit/9772494f4e6f9200e9350260cbae7f582522fb7a)

I finally got to look at this. z_exportwallet (line 462) and dumpwallet (line 483) in rpcdump.cpp are pretty much the same with z_exportwallet passing boolean true dumpwallet passing boolean false as the last param in calling dumpwallet_impl. Both dump ASCII text files.

backupwallet (line 1801) in rpcwallet.cpp starts off the same but is a lot different. Its output file type is a Berkeley DB file.

**Pull request closed without merging**
